export enum DNCSkillName {
	StandardFinish = "Standard Finish",
	SingleStandardFinish = "Single Standard Finish",
	DoubleStandardFinish = "Double Standard Finish",
	FinishingMove = "Finishing Move",
	LastDance = "Last Dance",
	TechnicalFinish = "Technical Finish",
	SingleTechnicalFinish = "Single Technical Finish",
	DoubleTechnicalFinish = "Double Technical Finish",
	TripleTechnicalFinish = "Triple Technical Finish",
	QuadrupleTechnicalFinish = "Quadruple Technical Finish",
	Tillana = "Tillana",
	Cascade = "Cascade",
	Fountain = "Fountain",
	ReverseCascade = "Reverse Cascade",
	Fountainfall = "Fountainfall",
	Windmill = "Windmill",
	Bladeshower = "Bladeshower",
	RisingWindmill = "Rising Windmill",
	Bloodshower = "Bloodshower",
	StandardStep = "Standard Step",
	TechnicalStep = "Technical Step",
	Emboite = "Emboite",
	Entrechat = "Entrechat",
	Jete = "Jete",
	Pirouette = "Pirouette",
	SaberDance = "Saber Dance",
	DanceOfTheDawn = "Dance of the Dawn",
	ClosedPosition = "Closed Position",
	FanDance = "Fan Dance",
	FanDance2 = "Fan Dance II",
	FanDance3 = "Fan Dance III",
	FanDance4 = "Fan Dance IV",
	EnAvant = "En Avant",
	Devilment = "Devilment",
	StarfallDance = "Starfall Dance",
	ShieldSamba = "Shield Samba",
	Flourish = "Flourish",
	Improvisation = "Improvisation",
	ImprovisedFinish = "Improvised Finish",
	CuringWaltz = "Curing Waltz",
	Ending = "Ending",
}

export enum DNCResourceType {
	// Gauge
	EspritGauge = "EspritGauge",
	FeatherGauge = "Feathers",
	StandardDance = "Standard Dance",
	TechnicalDance = "Technical Dance",

	// Buffs
	SilkenSymmetry = "Silken Symmetry",
	SilkenFlow = "Silken Flow",
	FlourishingSymmetry = "Flourishing Symmetry",
	FlourishingFlow = "Flourishing Flow",
	ThreefoldFanDance = "Threefold Fan Dance",
	FourfoldFanDance = "Fourfold Fan Dance",
	FinishingMoveReady = "Finishing Move Ready",
	FlourishingStarfall = "Flourishing Starfall",
	StandardStep = "Standard Step",
	TechnicalStep = "Technical Step",
	StandardFinish = "Standard Finish",
	LastDanceReady = "Last Dance Ready",
	TechnicalFinish = "Technical Finish",
	DanceOfTheDawnReady = "Dance of the Dawn Ready",
	FlourishingFinish = "Flourishing Finish",
	ClosedPosition = "Closed Position",
	Devilment = "Devilment",
	ShieldSamba = "Shield Samba",
	Improvisation = "Improvisation",
	RisingRhythm = "Rising Rhythm",
	ImprovisationRegen = "Improvisation Regen",
	ImprovisedFinish = "Improvised Finish",
	Esprit = "Esprit",

	// Partner buffs
	DancePartner = "Dance Partner",
	StandardFinishPartner = "Standard Finish Partner",
	EspritPartner = "Esprit Partner",
	EspritTechnical = "Esprit Technical",

	// Combos & other trackers
	CascadeCombo = "CascadeCombo",
	WindmillCombo = "WindmillCombo",
	StandardBonus = "StandardBonus",
	TechnicalBonus = "TechnicalBonus",
	PartySize = "PartySize",
}

export enum DNCCooldownType {
	cd_StandardStep = "cd_StandardStep",
	cd_TechnicalStep = "cd_TechnicalStep",
	cd_ClosedPosition = "cd_ClosedPosition",
	cd_FanDance = "cd_FanDance",
	cd_FanDanceII = "cd_FanDanceII",
	cd_FanDanceIII = "cd_FanDanceIII",
	cd_FanDanceIV = "cd_FanDanceIV",
	cd_EnAvant = "cd_EnAvant",
	cd_Devilment = "cd_Devilment",
	cd_ShieldSamba = "cd_ShieldSamba",
	cd_Flourish = "cd_Flourish",
	cd_Improvisation = "cd_Improvisation",
	cd_ImprovisedFinish = "cd_ImprovisedFinish",
	cd_CuringWaltz = "cd_CuringWaltz",
	cd_Ending = "cd_Ending",
}
